# Generated by Django 4.1.7 on 2023-04-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="item",),
        migrations.RemoveField(model_name="cart", name="quantity",),
        migrations.RemoveField(model_name="cart", name="special_instructions",),
        migrations.RemoveField(model_name="order", name="bill",),
        migrations.RemoveField(model_name="order", name="order_items",),
        migrations.RemoveField(model_name="orderitem", name="item",),
        migrations.RemoveField(model_name="orderitem", name="order",),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="ForkAndKnife.OrderItem", to="ForkAndKnife.menu"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ForkAndKnife.cart",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Cash on Delivery", max_length=30),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="ForkAndKnife.cart",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ForkAndKnife.menu",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
