# Generated by Django 4.1.7 on 2023-04-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="product",),
        migrations.RemoveField(model_name="billing", name="orderr",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderItem",),
    ]
