# Generated by Django 4.1.7 on 2023-04-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0002_remove_cart_item_remove_cart_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="cart",),
        migrations.RemoveField(model_name="orderitem", name="cart",),
        migrations.DeleteModel(name="Cart",),
    ]
