# Generated by Django 4.1.7 on 2023-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0003_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="number",
            field=models.CharField(max_length=10),
        ),
    ]
