# Generated by Django 4.1.7 on 2023-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0004_alter_customuser_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
