# Generated by Django 4.1.7 on 2023-04-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0005_bill"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
