# Generated by Django 4.1.7 on 2023-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="ForkAndKnife.menu"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Cash on Delivery", max_length=30),
        ),
        migrations.AddField(
            model_name="order", name="quantity", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
