# Generated by Django 4.1.7 on 2023-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0007_order_delivery_address_order_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="quantity", field=models.IntegerField(default=0),
        ),
    ]
