# Generated by Django 4.1.7 on 2023-04-28 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0007_billing_order_orderitem_delete_bill_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="customer",),
        migrations.AlterField(
            model_name="billing",
            name="orderr",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ForkAndKnife.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(default="", verbose_name=datetime.date),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ForkAndKnife.menu",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ForkAndKnife.order",
            ),
        ),
    ]
