# Generated by Django 4.1.7 on 2023-04-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0008_remove_order_customer_alter_billing_orderr_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="bill",),
        migrations.RemoveField(model_name="order", name="order_items",),
        migrations.RemoveField(model_name="orderitem", name="item",),
        migrations.RemoveField(model_name="orderitem", name="order",),
        migrations.DeleteModel(name="Billing",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderItem",),
    ]
