# Generated by Django 4.1.7 on 2023-04-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0010_alter_order_quantity"),
    ]

    operations = [
        migrations.DeleteModel(name="Order",),
    ]
