# Generated by Django 4.1.7 on 2023-04-30 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0011_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "payment_method",
                    models.CharField(default="Cash on Delivery", max_length=30),
                ),
                ("delivery_address", models.CharField(default="", max_length=100)),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False)),
                ("items", models.ManyToManyField(to="ForkAndKnife.menu")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
